version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: focus3_postgres
    restart: always
    environment:
      POSTGRES_USER: focus3_admin
      POSTGRES_PASSWORD: focus3_secret_password
      POSTGRES_DB: focus3_core
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mount file script SQL to auto run when container initializes for the first time
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - focus3_network

  redis:
    image: redis:7-alpine
    container_name: focus3_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - focus3_network

  adminer:
    image: adminer
    container_name: focus3_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - focus3_network

  # api:
  #   build: .
  #   container_name: focus3_api
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - POSTGRES_SERVER=db
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=username
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=focus3_core
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - focus3_network

volumes:
  pgdata:
  redisdata:

networks:
  focus3_network:
    driver: bridge