"""add audio_briefings table

Revision ID: 8e4a04500129
Revises: a529871d7d64
Create Date: 2026-03-06 23:25:41.146482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4a04500129'
down_revision: Union[str, Sequence[str], None] = 'a529871d7d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), server_default='vn', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_briefings_id'), 'audio_briefings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_briefings_id'), table_name='audio_briefings')
    op.drop_table('audio_briefings')
    # ### end Alembic commands ###
