"""add_description_to_articles

Revision ID: b1dbd8e522de
Revises: cea14abf3b44
Create Date: 2026-03-05 10:18:40.376261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dbd8e522de'
down_revision: Union[str, Sequence[str], None] = 'cea14abf3b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###
