"""add_region_and_language_to_sources

Revision ID: cea14abf3b44
Revises: 989797f6215e
Create Date: 2026-03-05 09:15:32.581475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea14abf3b44'
down_revision: Union[str, Sequence[str], None] = '989797f6215e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('region', sa.String(length=50), server_default='vn', nullable=False))
    op.add_column('sources', sa.Column('language', sa.String(length=10), server_default='vi', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'language')
    op.drop_column('sources', 'region')
    # ### end Alembic commands ###
