import os
import json
import logging
from datetime import datetime
from typing import Optional
from sqlalchemy.orm import Session, contains_eager
from google.cloud import texttospeech
from google.api_core.exceptions import GoogleAPIError

from app.models.models import Article, Category, Source, AudioBriefing
from app.core.config import settings
from app.services.ai.processor import openrouter_client

logger = logging.getLogger(__name__)

LANGUAGE_MAP = {
    "vi": "Vietnamese",
    "en": "English"
}

def generate_daily_briefing(db: Session, region: str = "vn") -> Optional[AudioBriefing]:
    f"""
    Generates a daily podcast-style audio briefing based on the top articles for a given region.
    - Queries top 3 articles per category matching the region (similar to feed logic).
    - Uses OpenRouter to generate a podcast script.
    - Uses gTTS to generate an MP3 file.
    - Saves the MP3 file to the static directory and a record in the database.
    """
    logger.info(f"Starting daily audio briefing generation for region: {region}")
    
    try:
        categories = db.query(Category).all()
        briefing_payload = []
        
        for category in categories:
            articles = (
                db.query(Article)
                .join(Source)
                .options(contains_eager(Article.source))
                .filter(
                    Article.category_id == category.id,
                    Article.ai_summary.isnot(None),
                    Source.region == region,
                    Source.is_active == True
                )
                .order_by(Article.importance_score.desc())
                .limit(3)
                .all()
            )
            
            if articles:
                category_data = {
                    "category_name": category.name,
                    "articles": []
                }
                for article in articles:
                    summary_points = article.ai_summary.get("summary", []) if isinstance(article.ai_summary, dict) else []
                    category_data["articles"].append({
                        "title": article.title,
                        "summary": summary_points
                    })
                briefing_payload.append(category_data)
                
        if not briefing_payload:
            logger.info("No summarized articles found to generate a briefing.")
            return None
            
        # Step 3.3: Call LLM to generate script
        prompt = f"""
        You are the professional host named "Phương Mai" of the Focus3 News Podcast.
        Write a 3 to 5-minute script using the provided news summaries.
        CRITICAL: Output the response wrapped in <speak> tags.
        Insert a <break time="800ms"/> when transitioning between different news categories,
        and <break time="400ms"/> between separate news items.
        Use natural, conversational Vietnamese.
        DO NOT output any markdown blocks (like ```xml) or non-SSML text.
        
        News Summaries Payload:
        {json.dumps(briefing_payload, ensure_ascii=False, indent=2)}
        """
        
        logger.info("Calling OpenRouter for script generation...")
        response = openrouter_client.chat.completions.create(
            model="google/gemma-3-27b-it",
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0.4
        )
        
        script_text = response.choices[0].message.content.strip()
        if not script_text:
            raise ValueError("Empty script generated by OpenRouter")
            
        logger.info("Script successfully generated. Converting to audio using Google Cloud TTS...")
        
        # Step 3.4 & 3.5: TTS to MP3
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"briefing_{timestamp}_{region}.mp3"
        
        # Ensure directory exists
        audio_dir = os.path.join(os.getcwd(), "app", "static", "audio")
        os.makedirs(audio_dir, exist_ok=True)
        
        filepath = os.path.join(audio_dir, filename)
        
        try:
            client = texttospeech.TextToSpeechClient()
            synthesis_input = texttospeech.SynthesisInput(ssml=script_text)
            
            voice = texttospeech.VoiceSelectionParams(
                language_code="vi-VN",
                name="vi-VN-Chirp3-HD-Leda"
            )
            
            audio_config = texttospeech.AudioConfig(
                audio_encoding=texttospeech.AudioEncoding.MP3,
                sample_rate_hertz=24000,
                speaking_rate=1.0
            )
            
            response_tts = client.synthesize_speech(
                input=synthesis_input, voice=voice, audio_config=audio_config
            )
            
            with open(filepath, "wb") as out:
                out.write(response_tts.audio_content)
                
            logger.info(f"Audio file saved locally to {filepath}")
        except GoogleAPIError as tts_err:
            logger.error(f"Google Cloud TTS API Error: {tts_err}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error during TTS synthesis: {e}")
            raise
        
        # Step 3.6: Calculate duration & Save to DB
        word_count = len(script_text.split())
        estimated_duration = int(word_count / 130 * 60) # approx 130 WPM
        
        audio_url = f"/static/audio/{filename}"
        
        briefing_record = AudioBriefing(
            title=f"Bản tin Focus3 - {datetime.now().strftime('%d/%m/%Y')}",
            audio_url=audio_url,
            duration_seconds=estimated_duration,
            region=region
        )
        
        db.add(briefing_record)
        db.commit()
        db.refresh(briefing_record)
        
        logger.info(f"Audio briefing generated and saved to DB with ID: {briefing_record.id}")
        return briefing_record
        
    except Exception as e:
        db.rollback()
        logger.error(f"Failed to generate audio briefing: {e}")
        return None
